name: eureka
channels:
    - conda-forge
    - defaults
dependencies:
    - python==3.9.7
    - asdf[version='>=2.7.1,<2.11.0'] # Needed for jwst==1.3.3
    - astropy
    - batman-package
    - bokeh
    - ccdproc
    - corner
    - cython
    - dynesty[version='>1.0']
    - emcee[version='>3.0.0']
    - george
    - gwcs
    - h5py
    - ipython
    - lmfit
    - matplotlib
    - nbsphinx # Needed for documentation
    - numpy[version='>=1.20.0']
    - pandas
    - photutils
    - pip # required for the pip installs below
    - pytest
    - recommonmark # Needed for documentation
    - requests
    - scipy[version='>=1.4.0'] # Needed for scipy.fft
    - tqdm
    - pip:
        - crds
        - jwst==1.3.3
        - myst-parser # Needed for documentation
        - sphinx-rtd-theme # Needed for documentation
        - stcal
        - stdatamodels
        - svo_filters
