name: Pytest Testing
on:
  pull_request:
    types: [opened,reopened,synchronize]
  push:
    branches:    
      - 'main'
      - 'releases/**'
jobs:
  test:
    name: pytest
    runs-on: 'ubuntu-latest'
    env:
      OS: 'ubuntu-latest'
      PYTHON: '3.9'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Setup Environment
        run: |
          python -m pip install --upgrade pip
          pip install .[jwst,hst,test]
          mkdir $HOME/crds_cache
          echo "CRDS_PATH=$HOME/crds_cache" >> $GITHUB_ENV
          echo "CRDS_SERVER_URL=https://jwst-crds.stsci.edu" >> $GITHUB_ENV
      - name: Run tests, generate coverage report
        run: pytest tests --cov=./src/ --cov-report=xml
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v2
        with:
          env_vars: OS,PYTHON
          files: ./coverage.xml
          fail_ci_if_error: true
          verbose: true
